package CityBuilder.load;

import CityBuilder.objects.Tile;
import Enums.TileType;

import com.badlogic.gdx.graphics.g2d.Batch;

public class setAttributes extends Data
{
	private Tile[] tile = new Tile[40001];
	
	public setAttributes(Tile[] tile)
	{
		this.tile = tile;
	}
	
	public void attributes()
	{
		//row 1
		tile[1].setAttributes( TileType.iron, available, false, 2000 );
		tile[2].setAttributes( TileType.iron, available, false, 2000 );
		tile[3].setAttributes( TileType.iron, available, false, 2000 );
		tile[4].setAttributes( TileType.iron, available, false, 2000 );
		tile[5].setAttributes( TileType.iron, available, false, 2000 );
		tile[6].setAttributes( TileType.iron, available, false, 2000 );
		tile[7].setAttributes( TileType.iron, available, false, 2000 );
		tile[8].setAttributes( TileType.iron, available, false, 2000 );
		tile[9].setAttributes( TileType.iron, available, false, 2000 );
		tile[10].setAttributes( TileType.grass, available, false, 2000 );
		tile[11].setAttributes( TileType.grass, available, false, 2000 );
		tile[12].setAttributes( TileType.grass, available, false, 2000 );
		tile[13].setAttributes( TileType.grass, available, false, 2000 );
		tile[14].setAttributes( TileType.grass, available, false, 2000 );
		tile[15].setAttributes( TileType.grass, available, false, 2000 );
		tile[16].setAttributes( TileType.water, available, false, 2000 );
		tile[17].setAttributes( TileType.water, available, false, 2000 );
		tile[18].setAttributes( TileType.water, available, false, 2000 );
		tile[19].setAttributes( TileType.water, available, false, 2000 );
		tile[20].setAttributes( TileType.grass, available, false, 2000 );
		tile[21].setAttributes( TileType.grass, available, false, 2000 );
		tile[22].setAttributes( TileType.grass, available, false, 2000 );
		tile[23].setAttributes( TileType.grass, available, false, 2000 );
		tile[24].setAttributes( TileType.grass, available, false, 2000 );
		tile[25].setAttributes( TileType.grass, available, false, 2000 );
		
		//row 2
		tile[26].setAttributes( TileType.iron, available, false, 2000 );
		tile[27].setAttributes( TileType.iron, available, false, 2000 );
		tile[28].setAttributes( TileType.iron, available, false, 2000 );
		tile[29].setAttributes( TileType.iron, available, false, 2000 );
		tile[30].setAttributes( TileType.iron, available, false, 2000 );
		tile[31].setAttributes( TileType.iron, available, false, 2000 );
		tile[32].setAttributes( TileType.iron, available, false, 2000 );
		tile[33].setAttributes( TileType.iron, available, false, 2000 );
		tile[34].setAttributes( TileType.iron, available, false, 2000 );
		tile[35].setAttributes( TileType.grass, available, false, 2000 );
		tile[36].setAttributes( TileType.grass, available, false, 2000 );
		tile[37].setAttributes( TileType.grass, available, false, 2000 );
		tile[38].setAttributes( TileType.grass, available, false, 2000 );
		tile[39].setAttributes( TileType.grass, available, false, 2000 );
		tile[40].setAttributes( TileType.water, available, false, 2000 );
		tile[41].setAttributes( TileType.water, available, false, 2000 );
		tile[42].setAttributes( TileType.water, available, false, 2000 );
		tile[43].setAttributes( TileType.water, available, false, 2000 );
		tile[44].setAttributes( TileType.water, available, false, 2000 );
		tile[45].setAttributes( TileType.grass, available, false, 2000 );
		tile[46].setAttributes( TileType.grass, available, false, 2000 );
		tile[47].setAttributes( TileType.grass, available, false, 2000 );
		tile[48].setAttributes( TileType.grass, available, false, 2000 );
		tile[49].setAttributes( TileType.grass, available, false, 2000 );
		tile[50].setAttributes( TileType.grass, available, false, 2000 );
		
		//row 3
		tile[51].setAttributes( TileType.iron, available, false, 2000 );
		tile[52].setAttributes( TileType.iron, available, false, 2000 );
		tile[53].setAttributes( TileType.iron, available, false, 2000 );
		tile[54].setAttributes( TileType.iron, available, false, 2000 );
		tile[55].setAttributes( TileType.iron, available, false, 2000 );
		tile[56].setAttributes( TileType.iron, available, false, 2000 );
		tile[57].setAttributes( TileType.iron, available, false, 2000 );
		tile[58].setAttributes( TileType.iron, available, false, 2000 );
		tile[59].setAttributes( TileType.grass, available, false, 2000 );
		tile[60].setAttributes( TileType.grass, available, false, 2000 );
		tile[61].setAttributes( TileType.grass, available, false, 2000 );
		tile[62].setAttributes( TileType.grass, available, false, 2000 );
		tile[63].setAttributes( TileType.grass, available, false, 2000 );
		tile[64].setAttributes( TileType.grass, available, false, 2000 );
		tile[65].setAttributes( TileType.water, available, false, 2000 );
		tile[66].setAttributes( TileType.water, available, false, 2000 );
		tile[67].setAttributes( TileType.water, available, false, 2000 );
		tile[68].setAttributes( TileType.water, available, false, 2000 );
		tile[69].setAttributes( TileType.grass, available, false, 2000 );
		tile[70].setAttributes( TileType.grass, available, false, 2000 );
		tile[71].setAttributes( TileType.grass, available, false, 2000 );
		tile[72].setAttributes( TileType.grass, available, false, 2000 );
		tile[73].setAttributes( TileType.grass, available, false, 2000 );
		tile[74].setAttributes( TileType.grass, available, false, 2000 );
		tile[75].setAttributes( TileType.grass, available, false, 2000 );
		
		//row 4
		tile[76].setAttributes( TileType.grass, available, false, 2000 );
		tile[77].setAttributes( TileType.grass, available, false, 2000 );
		tile[78].setAttributes( TileType.iron, available, false, 2000 );
		tile[79].setAttributes( TileType.iron, available, false, 2000 );
		tile[80].setAttributes( TileType.iron, available, false, 2000 );
		tile[81].setAttributes( TileType.iron, available, false, 2000 );
		tile[82].setAttributes( TileType.iron, available, false, 2000 );
		tile[83].setAttributes( TileType.iron, available, false, 2000 );
		tile[84].setAttributes( TileType.grass, available, false, 2000 );
		tile[85].setAttributes( TileType.grass, available, false, 2000 );
		tile[86].setAttributes( TileType.grass, available, false, 2000 );
		tile[87].setAttributes( TileType.grass, available, false, 2000 );
		tile[88].setAttributes( TileType.grass, available, false, 2000 );
		tile[89].setAttributes( TileType.water, available, false, 2000 );
		tile[90].setAttributes( TileType.water, available, false, 2000 );
		tile[91].setAttributes( TileType.water, available, false, 2000 );
		tile[92].setAttributes( TileType.water, available, false, 2000 );
		tile[93].setAttributes( TileType.water, available, false, 2000 );
		tile[94].setAttributes( TileType.grass, available, false, 2000 );
		tile[95].setAttributes( TileType.grass, available, false, 2000 );
		tile[96].setAttributes( TileType.grass, available, false, 2000 );
		tile[97].setAttributes( TileType.grass, available, false, 2000 );
		tile[98].setAttributes( TileType.grass, available, false, 2000 );
		tile[99].setAttributes( TileType.grass, available, false, 2000 );
		tile[100].setAttributes( TileType.grass, available, false, 2000 );
		
		//row 5
		tile[101].setAttributes( TileType.grass, available, false, 2000 );
		tile[102].setAttributes( TileType.grass, available, false, 2000 );
		tile[103].setAttributes( TileType.grass, available, false, 2000 );
		tile[104].setAttributes( TileType.grass, available, false, 2000 );
		tile[105].setAttributes( TileType.iron, available, false, 2000 );
		tile[106].setAttributes( TileType.iron, available, false, 2000 );
		tile[107].setAttributes( TileType.iron, available, false, 2000 );
		tile[108].setAttributes( TileType.grass, available, false, 2000 );
		tile[109].setAttributes( TileType.grass, available, false, 2000 );
		tile[110].setAttributes( TileType.grass, available, false, 2000 );
		tile[111].setAttributes( TileType.grass, available, false, 2000 );
		tile[112].setAttributes( TileType.water, available, false, 2000 );
		tile[113].setAttributes( TileType.water, available, false, 2000 );
		tile[114].setAttributes( TileType.water, available, false, 2000 );
		tile[115].setAttributes( TileType.water, available, false, 2000 );
		tile[116].setAttributes( TileType.water, available, false, 2000 );
		tile[117].setAttributes( TileType.grass, available, false, 2000 );
		tile[118].setAttributes( TileType.grass, available, false, 2000 );
		tile[119].setAttributes( TileType.grass, available, false, 2000 );
		tile[120].setAttributes( TileType.grass, available, false, 2000 );
		tile[121].setAttributes( TileType.grass, available, false, 2000 );
		tile[122].setAttributes( TileType.grass, available, false, 2000 );
		tile[123].setAttributes( TileType.grass, available, false, 2000 );
		tile[124].setAttributes( TileType.grass, available, false, 2000 );
		tile[125].setAttributes( TileType.grass, available, false, 2000 );
		
		//row 6
		tile[126].setAttributes( TileType.grass, available, false, 2000 );
		tile[127].setAttributes( TileType.grass, available, false, 2000 );
		tile[128].setAttributes( TileType.grass, available, false, 2000 );
		tile[129].setAttributes( TileType.grass, available, false, 2000 );
		tile[130].setAttributes( TileType.iron, available, false, 2000 );
		tile[131].setAttributes( TileType.iron, available, false, 2000 );
		tile[132].setAttributes( TileType.grass, available, false, 2000 );
		tile[133].setAttributes( TileType.grass, available, false, 2000 );
		tile[134].setAttributes( TileType.water, available, false, 2000 );
		tile[135].setAttributes( TileType.water, available, false, 2000 );
		tile[136].setAttributes( TileType.water, available, false, 2000 );
		tile[137].setAttributes( TileType.water, available, false, 2000 );
		tile[138].setAttributes( TileType.water, available, false, 2000 );
		tile[139].setAttributes( TileType.water, available, false, 2000 );
		tile[140].setAttributes( TileType.water, available, false, 2000 );
		tile[141].setAttributes( TileType.water, available, false, 2000 );
		tile[142].setAttributes( TileType.grass, available, false, 2000 );
		tile[143].setAttributes( TileType.iron, available, false, 2000 );
		tile[144].setAttributes( TileType.iron, available, false, 2000 );
		tile[145].setAttributes( TileType.grass, available, false, 2000 );
		tile[146].setAttributes( TileType.grass, available, false, 2000 );
		tile[147].setAttributes( TileType.grass, available, false, 2000 );
		tile[148].setAttributes( TileType.grass, available, false, 2000 );
		tile[149].setAttributes( TileType.grass, available, false, 2000 );
		tile[150].setAttributes( TileType.grass, available, false, 2000 );
		
		//row 7
		tile[151].setAttributes( TileType.grass, available, false, 2000 );
		tile[152].setAttributes( TileType.grass, available, false, 2000 );
		tile[153].setAttributes( TileType.grass, available, false, 2000 );
		tile[154].setAttributes( TileType.grass, available, false, 2000 );
		tile[155].setAttributes( TileType.grass, available, false, 2000 );
		tile[156].setAttributes( TileType.grass, available, false, 2000 );
		tile[157].setAttributes( TileType.grass, available, false, 2000 );
		tile[158].setAttributes( TileType.water, available, false, 2000 );
		tile[159].setAttributes( TileType.water, available, false, 2000 );
		tile[160].setAttributes( TileType.water, available, false, 2000 );
		tile[161].setAttributes( TileType.water, available, false, 2000 );
		tile[162].setAttributes( TileType.water, available, false, 2000 );
		tile[163].setAttributes( TileType.water, available, false, 2000 );
		tile[164].setAttributes( TileType.water, available, false, 2000 );
		tile[165].setAttributes( TileType.grass, available, false, 2000 );
		tile[166].setAttributes( TileType.grass, available, false, 2000 );
		tile[167].setAttributes( TileType.grass, available, false, 2000 );
		tile[168].setAttributes( TileType.iron, available, false, 2000 );
		tile[169].setAttributes( TileType.iron, available, false, 2000 );
		tile[170].setAttributes( TileType.grass, available, false, 2000 );
		tile[171].setAttributes( TileType.grass, available, false, 2000 );
		tile[172].setAttributes( TileType.grass, available, false, 2000 );
		tile[173].setAttributes( TileType.grass, available, false, 2000 );
		tile[174].setAttributes( TileType.grass, available, false, 2000 );
		tile[175].setAttributes( TileType.grass, available, false, 2000 );
		
		//row 8
		tile[151].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[152].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[153].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[154].setAttributes( TileType.grass, available, false, 2000 );
		tile[155].setAttributes( TileType.grass, available, false, 2000 );
		tile[156].setAttributes( TileType.grass, available, false, 2000 );
		tile[157].setAttributes( TileType.grass, available, false, 2000 );
		tile[158].setAttributes( TileType.water, available, false, 2000 );
		tile[159].setAttributes( TileType.water, available, false, 2000 );
		tile[160].setAttributes( TileType.water, available, false, 2000 );
		tile[161].setAttributes( TileType.water, available, false, 2000 );
		tile[162].setAttributes( TileType.water, available, false, 2000 );
		tile[163].setAttributes( TileType.water, available, false, 2000 );
		tile[164].setAttributes( TileType.grass, available, false, 2000 );
		tile[165].setAttributes( TileType.grass, available, false, 2000 );
		tile[166].setAttributes( TileType.iron, available, false, 2000 );
		tile[167].setAttributes( TileType.iron, available, false, 2000 );
		tile[168].setAttributes( TileType.iron, available, false, 2000 );
		tile[169].setAttributes( TileType.iron, available, false, 2000 );
		tile[170].setAttributes( TileType.grass, available, false, 2000 );
		tile[171].setAttributes( TileType.grass, available, false, 2000 );
		tile[172].setAttributes( TileType.grass, available, false, 2000 );
		tile[173].setAttributes( TileType.grass, available, false, 2000 );
		tile[174].setAttributes( TileType.grass, available, false, 2000 );
		tile[175].setAttributes( TileType.grass, available, false, 2000 );
		
		//row 9
		tile[176].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[177].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[178].setAttributes( TileType.grass, available, false, 2000 );
		tile[179].setAttributes( TileType.grass, available, false, 2000 );
		tile[180].setAttributes( TileType.grass, available, false, 2000 );
		tile[181].setAttributes( TileType.water, available, false, 2000 );
		tile[182].setAttributes( TileType.water, available, false, 2000 );
		tile[183].setAttributes( TileType.water, available, false, 2000 );
		tile[184].setAttributes( TileType.water, available, false, 2000 );
		tile[185].setAttributes( TileType.water, available, false, 2000 );
		tile[186].setAttributes( TileType.grass, available, false, 2000 );
		tile[187].setAttributes( TileType.grass, available, false, 2000 );
		tile[188].setAttributes( TileType.grass, available, false, 2000 );
		tile[189].setAttributes( TileType.iron, available, false, 2000 );
		tile[190].setAttributes( TileType.iron, available, false, 2000 );
		tile[191].setAttributes( TileType.iron, available, false, 2000 );
		tile[192].setAttributes( TileType.iron, available, false, 2000 );
		tile[193].setAttributes( TileType.iron, available, false, 2000 );
		tile[194].setAttributes( TileType.grass, available, false, 2000 );
		tile[195].setAttributes( TileType.grass, available, false, 2000 );
		tile[196].setAttributes( TileType.grass, available, false, 2000 );
		tile[197].setAttributes( TileType.wood, available, false, 2000 );
		tile[198].setAttributes( TileType.grass, available, false, 2000 );
		tile[199].setAttributes( TileType.grass, available, false, 2000 );
		tile[200].setAttributes( TileType.grass, available, false, 2000 );
		
		//row 10
		tile[201].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[202].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[203].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[204].setAttributes( TileType.grass, available, false, 2000 );
		tile[205].setAttributes( TileType.grass, available, false, 2000 );
		tile[206].setAttributes( TileType.water, available, false, 2000 );
		tile[207].setAttributes( TileType.water, available, false, 2000 );
		tile[208].setAttributes( TileType.water, available, false, 2000 );
		tile[209].setAttributes( TileType.water, available, false, 2000 );
		tile[210].setAttributes( TileType.water, available, false, 2000 );
		tile[211].setAttributes( TileType.grass, available, false, 2000 );
		tile[212].setAttributes( TileType.grass, available, false, 2000 );
		tile[213].setAttributes( TileType.grass, available, false, 2000 );
		tile[214].setAttributes( TileType.iron, available, false, 2000 );
		tile[215].setAttributes( TileType.iron, available, false, 2000 );
		tile[216].setAttributes( TileType.iron, available, false, 2000 );
		tile[217].setAttributes( TileType.iron, available, false, 2000 );
		tile[218].setAttributes( TileType.grass, available, false, 2000 );
		tile[219].setAttributes( TileType.grass, available, false, 2000 );
		tile[220].setAttributes( TileType.grass, available, false, 2000 );
		tile[221].setAttributes( TileType.wood, available, false, 2000 );
		tile[222].setAttributes( TileType.wood, available, false, 2000 );
		tile[223].setAttributes( TileType.wood, available, false, 2000 );
		tile[224].setAttributes( TileType.grass, available, false, 2000 );
		tile[225].setAttributes( TileType.grass, available, false, 2000 );
		
		//row 11
		tile[226].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[227].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[228].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[229].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[230].setAttributes( TileType.grass, available, false, 2000 );
		tile[231].setAttributes( TileType.water, available, false, 2000 );
		tile[232].setAttributes( TileType.water, available, false, 2000 );
		tile[233].setAttributes( TileType.water, available, false, 2000 );
		tile[234].setAttributes( TileType.water, available, false, 2000 );
		tile[235].setAttributes( TileType.water, available, false, 2000 );
		tile[236].setAttributes( TileType.grass, available, false, 2000 );
		tile[237].setAttributes( TileType.grass, available, false, 2000 );
		tile[238].setAttributes( TileType.grass, available, false, 2000 );
		tile[239].setAttributes( TileType.grass, available, false, 2000 );
		tile[240].setAttributes( TileType.grass, available, false, 2000 );
		tile[241].setAttributes( TileType.grass, available, false, 2000 );
		tile[242].setAttributes( TileType.grass, available, false, 2000 );
		tile[243].setAttributes( TileType.grass, available, false, 2000 );
		tile[244].setAttributes( TileType.grass, available, false, 2000 );
		tile[245].setAttributes( TileType.wood, available, false, 2000 );
		tile[246].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[247].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[248].setAttributes( TileType.wood, available, false, 2000 );
		tile[249].setAttributes( TileType.grass, available, false, 2000 );
		tile[250].setAttributes( TileType.grass, available, false, 2000 );
		
		//row 12
		tile[251].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[252].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[253].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[254].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[255].setAttributes( TileType.water, available, false, 2000 );
		tile[256].setAttributes( TileType.water, available, false, 2000 );
		tile[257].setAttributes( TileType.water, available, false, 2000 );
		tile[258].setAttributes( TileType.water, available, false, 2000 );
		tile[259].setAttributes( TileType.water, available, false, 2000 );
		tile[260].setAttributes( TileType.water, available, false, 2000 );
		tile[261].setAttributes( TileType.grass, available, false, 2000 );
		tile[262].setAttributes( TileType.grass, available, false, 2000 );
		tile[263].setAttributes( TileType.grass, available, false, 2000 );
		tile[264].setAttributes( TileType.grass, available, false, 2000 );
		tile[265].setAttributes( TileType.grass, available, false, 2000 );
		tile[266].setAttributes( TileType.grass, available, false, 2000 );
		tile[267].setAttributes( TileType.grass, available, false, 2000 );
		tile[268].setAttributes( TileType.grass, available, false, 2000 );
		tile[269].setAttributes( TileType.wood, available, false, 2000 );
		tile[270].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[271].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[272].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[273].setAttributes( TileType.grass, available, false, 2000 );
		tile[274].setAttributes( TileType.grass, available, false, 2000 );
		tile[275].setAttributes( TileType.grass, available, false, 2000 );
		
		//row 13
		tile[276].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[277].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[278].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[279].setAttributes( TileType.grass, available, false, 2000 );
		tile[280].setAttributes( TileType.grass, available, false, 2000 );
		tile[281].setAttributes( TileType.water, available, false, 2000 );
		tile[282].setAttributes( TileType.water, available, false, 2000 );
		tile[283].setAttributes( TileType.water, available, false, 2000 );
		tile[284].setAttributes( TileType.water, available, false, 2000 );
		tile[285].setAttributes( TileType.water, available, false, 2000 );
		tile[286].setAttributes( TileType.grass, available, false, 2000 );
		tile[287].setAttributes( TileType.grass, available, false, 2000 );
		tile[288].setAttributes( TileType.town, available, false, 2000 );
		tile[289].setAttributes( TileType.grass, available, false, 2000 );
		tile[290].setAttributes( TileType.grass, available, false, 2000 );
		tile[291].setAttributes( TileType.grass, available, false, 2000 );
		tile[292].setAttributes( TileType.grass, available, false, 2000 );
		tile[293].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[294].setAttributes( TileType.wood, available, false, 2000 );
		tile[295].setAttributes( TileType.wood, available, false, 2000 );
		tile[296].setAttributes( TileType.wood, available, false, 2000 );
		tile[297].setAttributes( TileType.grass, available, false, 2000 );
		tile[298].setAttributes( TileType.grass, available, false, 2000 );
		tile[299].setAttributes( TileType.grass, available, false, 2000 );
		tile[300].setAttributes( TileType.grass, available, false, 2000 );
		
		//row 14
		tile[301].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[302].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[303].setAttributes( TileType.grass, available, false, 2000 );
		tile[304].setAttributes( TileType.grass, available, false, 2000 );
		tile[305].setAttributes( TileType.grass, available, false, 2000 );
		tile[306].setAttributes( TileType.water, available, false, 2000 );
		tile[307].setAttributes( TileType.water, available, false, 2000 );
		tile[308].setAttributes( TileType.water, available, false, 2000 );
		tile[309].setAttributes( TileType.water, available, false, 2000 );
		tile[310].setAttributes( TileType.water, available, false, 2000 );
		tile[311].setAttributes( TileType.grass, available, false, 2000 );
		tile[312].setAttributes( TileType.grass, available, false, 2000 );
		tile[313].setAttributes( TileType.grass, available, false, 2000 );
		tile[314].setAttributes( TileType.grass, available, false, 2000 );
		tile[315].setAttributes( TileType.wood, available, false, 2000 );
		tile[316].setAttributes( TileType.wood, available, false, 2000 );
		tile[317].setAttributes( TileType.wood, available, false, 2000 );
		tile[318].setAttributes( TileType.wood, available, false, 2000 );
		tile[319].setAttributes( TileType.wood, available, false, 2000 );
		tile[320].setAttributes( TileType.grass, available, false, 2000 );
		tile[321].setAttributes( TileType.grass, available, false, 2000 );
		tile[322].setAttributes( TileType.grass, available, false, 2000 );
		tile[323].setAttributes( TileType.grass, available, false, 2000 );
		tile[324].setAttributes( TileType.grass, available, false, 2000 );
		tile[325].setAttributes( TileType.grass, available, false, 2000 );
		
		//row 15
		tile[326].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[327].setAttributes( TileType.wood, available, false, 2000 );
		tile[328].setAttributes( TileType.wood, available, false, 2000 );
		tile[329].setAttributes( TileType.wood, available, false, 2000 );
		tile[330].setAttributes( TileType.grass, available, false, 2000 );
		tile[331].setAttributes( TileType.grass, available, false, 2000 );
		tile[332].setAttributes( TileType.water, available, false, 2000 );
		tile[333].setAttributes( TileType.water, available, false, 2000 );
		tile[334].setAttributes( TileType.water, available, false, 2000 );
		tile[335].setAttributes( TileType.water, available, false, 2000 );
		tile[336].setAttributes( TileType.grass, available, false, 2000 );
		tile[337].setAttributes( TileType.grass, available, false, 2000 );
		tile[338].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[339].setAttributes( TileType.wood, available, false, 2000 );
		tile[340].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[341].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[342].setAttributes( TileType.wood, available, false, 2000 );
		tile[343].setAttributes( TileType.wood, available, false, 2000 );
		tile[344].setAttributes( TileType.wood, available, false, 2000 );
		tile[345].setAttributes( TileType.grass, available, false, 2000 );
		tile[346].setAttributes( TileType.grass, available, false, 2000 );
		tile[347].setAttributes( TileType.grass, available, false, 2000 );
		tile[348].setAttributes( TileType.grass, available, false, 2000 );
		tile[349].setAttributes( TileType.grass, available, false, 2000 );
		tile[350].setAttributes( TileType.grass, available, false, 2000 );
		
		//row 16
		tile[351].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[352].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[353].setAttributes( TileType.wood, available, false, 2000 );
		tile[354].setAttributes( TileType.wood, available, false, 2000 );
		tile[355].setAttributes( TileType.grass, available, false, 2000 );
		tile[356].setAttributes( TileType.grass, available, false, 2000 );
		tile[357].setAttributes( TileType.water, available, false, 2000 );
		tile[358].setAttributes( TileType.water, available, false, 2000 );
		tile[359].setAttributes( TileType.water, available, false, 2000 );
		tile[360].setAttributes( TileType.water, available, false, 2000 );
		tile[361].setAttributes( TileType.grass, available, false, 2000 );
		tile[362].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[363].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[364].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[365].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[366].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[367].setAttributes( TileType.wood, available, false, 2000 );
		tile[368].setAttributes( TileType.grass, available, false, 2000 );
		tile[369].setAttributes( TileType.grass, available, false, 2000 );
		tile[370].setAttributes( TileType.grass, available, false, 2000 );
		tile[371].setAttributes( TileType.grass, available, false, 2000 );
		tile[372].setAttributes( TileType.grass, available, false, 2000 );
		tile[373].setAttributes( TileType.grass, available, false, 2000 );
		tile[374].setAttributes( TileType.grass, available, false, 2000 );
		tile[375].setAttributes( TileType.grass, available, false, 2000 );
		
		//row 17
		tile[376].setAttributes( TileType.wood, available, false, 2000 );
		tile[377].setAttributes( TileType.wood, available, false, 2000 );
		tile[378].setAttributes( TileType.wood, available, false, 2000 );
		tile[379].setAttributes( TileType.wood, available, false, 2000 );
		tile[380].setAttributes( TileType.water, available, false, 2000 );
		tile[381].setAttributes( TileType.water, available, false, 2000 );
		tile[382].setAttributes( TileType.water, available, false, 2000 );
		tile[383].setAttributes( TileType.water, available, false, 2000 );
		tile[384].setAttributes( TileType.water, available, false, 2000 );
		tile[385].setAttributes( TileType.water, available, false, 2000 );
		tile[386].setAttributes( TileType.grass, available, false, 2000 );
		tile[387].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[388].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[389].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[390].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[391].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[392].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[393].setAttributes( TileType.grass, available, false, 2000 );
		tile[394].setAttributes( TileType.grass, available, false, 2000 );
		tile[395].setAttributes( TileType.grass, available, false, 2000 );
		tile[396].setAttributes( TileType.grass, available, false, 2000 );
		tile[397].setAttributes( TileType.grass, available, false, 2000 );
		tile[398].setAttributes( TileType.grass, available, false, 2000 );
		tile[399].setAttributes( TileType.grass, available, false, 2000 );
		tile[400].setAttributes( TileType.grass, available, false, 2000 );
		
		//row 18
		tile[401].setAttributes( TileType.wood, available, false, 2000 );
		tile[402].setAttributes( TileType.wood, available, false, 2000 );
		tile[403].setAttributes( TileType.wood, available, false, 2000 );
		tile[404].setAttributes( TileType.wood, available, false, 2000 );
		tile[405].setAttributes( TileType.grass, available, false, 2000 );
		tile[406].setAttributes( TileType.water, available, false, 2000 );
		tile[407].setAttributes( TileType.water, available, false, 2000 );
		tile[408].setAttributes( TileType.water, available, false, 2000 );
		tile[409].setAttributes( TileType.water, available, false, 2000 );
		tile[410].setAttributes( TileType.water, available, false, 2000 );
		tile[411].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[412].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[413].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[414].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[415].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[416].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[417].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[418].setAttributes( TileType.grass, available, false, 2000 );
		tile[419].setAttributes( TileType.grass, available, false, 2000 );
		tile[420].setAttributes( TileType.grass, available, false, 2000 );
		tile[421].setAttributes( TileType.grass, available, false, 2000 );
		tile[422].setAttributes( TileType.grass, available, false, 2000 );
		tile[423].setAttributes( TileType.grass, available, false, 2000 );
		tile[424].setAttributes( TileType.grass, available, false, 2000 );
		tile[425].setAttributes( TileType.grass, available, false, 2000 );
		
		//row 19
		tile[426].setAttributes( TileType.wood, available, false, 2000 );
		tile[427].setAttributes( TileType.wood, available, false, 2000 );
		tile[428].setAttributes( TileType.wood, available, false, 2000 );
		tile[429].setAttributes( TileType.wood, available, false, 2000 );
		tile[430].setAttributes( TileType.grass, available, false, 2000 );
		tile[431].setAttributes( TileType.grass, available, false, 2000 );
		tile[432].setAttributes( TileType.water, available, false, 2000 );
		tile[433].setAttributes( TileType.water, available, false, 2000 );
		tile[434].setAttributes( TileType.water, available, false, 2000 );
		tile[435].setAttributes( TileType.water, available, false, 2000 );
		tile[436].setAttributes( TileType.grass, available, false, 2000 );
		tile[437].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[438].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[439].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[440].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[441].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[442].setAttributes( TileType.wood, available, false, 2000 );
		tile[443].setAttributes( TileType.wood, available, false, 2000 );
		tile[444].setAttributes( TileType.grass, available, false, 2000 );
		tile[445].setAttributes( TileType.grass, available, false, 2000 );
		tile[446].setAttributes( TileType.grass, available, false, 2000 );
		tile[447].setAttributes( TileType.grass, available, false, 2000 );
		tile[448].setAttributes( TileType.grass, available, false, 2000 );
		tile[449].setAttributes( TileType.grass, available, false, 2000 );
		tile[450].setAttributes( TileType.grass, available, false, 2000 );
		
		//row 20
		tile[451].setAttributes( TileType.wood, available, false, 2000 );
		tile[452].setAttributes( TileType.wood, available, false, 2000 );
		tile[453].setAttributes( TileType.wood, available, false, 2000 );
		tile[454].setAttributes( TileType.grass, available, false, 2000 );
		tile[455].setAttributes( TileType.grass, available, false, 2000 );
		tile[456].setAttributes( TileType.grass, available, false, 2000 );
		tile[457].setAttributes( TileType.water, available, false, 2000 );
		tile[458].setAttributes( TileType.water, available, false, 2000 );
		tile[459].setAttributes( TileType.water, available, false, 2000 );
		tile[460].setAttributes( TileType.water, available, false, 2000 );
		tile[461].setAttributes( TileType.grass, available, false, 2000 );
		tile[462].setAttributes( TileType.grass, available, false, 2000 );
		tile[463].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[464].setAttributes( TileType.dwayne, available, false, 2000 );
		tile[465].setAttributes( TileType.wood, available, false, 2000 );
		tile[466].setAttributes( TileType.wood, available, false, 2000 );
		tile[467].setAttributes( TileType.wood, available, false, 2000 );
		tile[468].setAttributes( TileType.wood, available, false, 2000 );
		tile[469].setAttributes( TileType.wood, available, false, 2000 );
		tile[470].setAttributes( TileType.wood, available, false, 2000 );
		tile[471].setAttributes( TileType.grass, available, false, 2000 );
		tile[472].setAttributes( TileType.grass, available, false, 2000 );
		tile[473].setAttributes( TileType.grass, available, false, 2000 );
		tile[474].setAttributes( TileType.grass, available, false, 2000 );
		tile[475].setAttributes( TileType.grass, available, false, 2000 );
		
		//row 21
		tile[476].setAttributes( TileType.wood, available, false, 2000 );
		tile[477].setAttributes( TileType.wood, available, false, 2000 );
		tile[478].setAttributes( TileType.wood, available, false, 2000 );
		tile[479].setAttributes( TileType.grass, available, false, 2000 );
		tile[480].setAttributes( TileType.grass, available, false, 2000 );
		tile[481].setAttributes( TileType.grass, available, false, 2000 );
		tile[482].setAttributes( TileType.grass, available, false, 2000 );
		tile[483].setAttributes( TileType.water, available, false, 2000 );
		tile[484].setAttributes( TileType.water, available, false, 2000 );
		tile[485].setAttributes( TileType.water, available, false, 2000 );
		tile[486].setAttributes( TileType.water, available, false, 2000 );
		tile[487].setAttributes( TileType.water, available, false, 2000 );
		tile[488].setAttributes( TileType.grass, available, false, 2000 );
		tile[489].setAttributes( TileType.grass, available, false, 2000 );
		tile[490].setAttributes( TileType.wood, available, false, 2000 );
		tile[491].setAttributes( TileType.wood, available, false, 2000 );
		tile[492].setAttributes( TileType.wood, available, false, 2000 );
		tile[493].setAttributes( TileType.wood, available, false, 2000 );
		tile[494].setAttributes( TileType.wood, available, false, 2000 );
		tile[495].setAttributes( TileType.wood, available, false, 2000 );
		tile[496].setAttributes( TileType.wood, available, false, 2000 );
		tile[497].setAttributes( TileType.grass, available, false, 2000 );
		tile[498].setAttributes( TileType.grass, available, false, 2000 );
		tile[499].setAttributes( TileType.grass, available, false, 2000 );
		tile[500].setAttributes( TileType.grass, available, false, 2000 );
		
		//row 22
		tile[501].setAttributes( TileType.wood, available, false, 2000 );
		tile[502].setAttributes( TileType.wood, available, false, 2000 );
		tile[503].setAttributes( TileType.grass, available, false, 2000 );
		tile[504].setAttributes( TileType.grass, available, false, 2000 );
		tile[505].setAttributes( TileType.grass, available, false, 2000 );
		tile[506].setAttributes( TileType.grass, available, false, 2000 );
		tile[507].setAttributes( TileType.grass, available, false, 2000 );
		tile[508].setAttributes( TileType.grass, available, false, 2000 );
		tile[509].setAttributes( TileType.water, available, false, 2000 );
		tile[510].setAttributes( TileType.water, available, false, 2000 );
		tile[511].setAttributes( TileType.water, available, false, 2000 );
		tile[512].setAttributes( TileType.water, available, false, 2000 );
		tile[513].setAttributes( TileType.grass, available, false, 2000 );
		tile[514].setAttributes( TileType.grass, available, false, 2000 );
		tile[515].setAttributes( TileType.wood, available, false, 2000 );
		tile[516].setAttributes( TileType.wood, available, false, 2000 );
		tile[517].setAttributes( TileType.wood, available, false, 2000 );
		tile[518].setAttributes( TileType.wood, available, false, 2000 );
		tile[519].setAttributes( TileType.wood, available, false, 2000 );
		tile[520].setAttributes( TileType.wood, available, false, 2000 );
		tile[521].setAttributes( TileType.wood, available, false, 2000 );
		tile[522].setAttributes( TileType.grass, available, false, 2000 );
		tile[523].setAttributes( TileType.grass, available, false, 2000 );
		tile[524].setAttributes( TileType.grass, available, false, 2000 );
		tile[525].setAttributes( TileType.grass, available, false, 2000 );
		
		//row 23
		tile[526].setAttributes( TileType.wood, available, false, 2000 );
		tile[527].setAttributes( TileType.wood, available, false, 2000 );
		tile[528].setAttributes( TileType.grass, available, false, 2000 );
		tile[529].setAttributes( TileType.grass, available, false, 2000 );
		tile[530].setAttributes( TileType.grass, available, false, 2000 );
		tile[531].setAttributes( TileType.grass, available, false, 2000 );
		tile[532].setAttributes( TileType.grass, available, false, 2000 );
		tile[533].setAttributes( TileType.grass, available, false, 2000 );
		tile[534].setAttributes( TileType.water, available, false, 2000 );
		tile[535].setAttributes( TileType.water, available, false, 2000 );
		tile[536].setAttributes( TileType.water, available, false, 2000 );
		tile[537].setAttributes( TileType.water, available, false, 2000 );
		tile[538].setAttributes( TileType.water, available, false, 2000 );
		tile[539].setAttributes( TileType.grass, available, false, 2000 );
		tile[540].setAttributes( TileType.grass, available, false, 2000 );
		tile[541].setAttributes( TileType.wood, available, false, 2000 );
		tile[542].setAttributes( TileType.wood, available, false, 2000 );
		tile[543].setAttributes( TileType.wood, available, false, 2000 );
		tile[544].setAttributes( TileType.wood, available, false, 2000 );
		tile[545].setAttributes( TileType.wood, available, false, 2000 );
		tile[546].setAttributes( TileType.grass, available, false, 2000 );
		tile[547].setAttributes( TileType.grass, available, false, 2000 );
		tile[548].setAttributes( TileType.grass, available, false, 2000 );
		tile[549].setAttributes( TileType.grass, available, false, 2000 );
		tile[550].setAttributes( TileType.grass, available, false, 2000 );
		
		//row 24
		tile[551].setAttributes( TileType.wood, available, false, 2000 );
		tile[552].setAttributes( TileType.wood, available, false, 2000 );
		tile[553].setAttributes( TileType.grass, available, false, 2000 );
		tile[554].setAttributes( TileType.grass, available, false, 2000 );
		tile[555].setAttributes( TileType.grass, available, false, 2000 );
		tile[556].setAttributes( TileType.grass, available, false, 2000 );
		tile[557].setAttributes( TileType.grass, available, false, 2000 );
		tile[558].setAttributes( TileType.grass, available, false, 2000 );
		tile[559].setAttributes( TileType.grass, available, false, 2000 );
		tile[560].setAttributes( TileType.water, available, false, 2000 );
		tile[561].setAttributes( TileType.water, available, false, 2000 );
		tile[562].setAttributes( TileType.water, available, false, 2000 );
		tile[563].setAttributes( TileType.water, available, false, 2000 );
		tile[564].setAttributes( TileType.water, available, false, 2000 );
		tile[565].setAttributes( TileType.grass, available, false, 2000 );
		tile[566].setAttributes( TileType.grass, available, false, 2000 );
		tile[567].setAttributes( TileType.grass, available, false, 2000 );
		tile[568].setAttributes( TileType.wood, available, false, 2000 );
		tile[569].setAttributes( TileType.wood, available, false, 2000 );
		tile[570].setAttributes( TileType.wood, available, false, 2000 );
		tile[571].setAttributes( TileType.grass, available, false, 2000 );
		tile[572].setAttributes( TileType.grass, available, false, 2000 );
		tile[573].setAttributes( TileType.grass, available, false, 2000 );
		tile[574].setAttributes( TileType.grass, available, false, 2000 );
		tile[575].setAttributes( TileType.grass, available, false, 2000 );
		
		//row 24
		tile[576].setAttributes( TileType.wood, available, false, 2000 );
		tile[577].setAttributes( TileType.grass, available, false, 2000 );
		tile[578].setAttributes( TileType.grass, available, false, 2000 );
		tile[579].setAttributes( TileType.grass, available, false, 2000 );
		tile[580].setAttributes( TileType.grass, available, false, 2000 );
		tile[581].setAttributes( TileType.grass, available, false, 2000 );
		tile[582].setAttributes( TileType.grass, available, false, 2000 );
		tile[583].setAttributes( TileType.grass, available, false, 2000 );
		tile[584].setAttributes( TileType.grass, available, false, 2000 );
		tile[585].setAttributes( TileType.grass, available, false, 2000 );
		tile[586].setAttributes( TileType.water, available, false, 2000 );
		tile[587].setAttributes( TileType.water, available, false, 2000 );
		tile[588].setAttributes( TileType.water, available, false, 2000 );
		tile[589].setAttributes( TileType.water, available, false, 2000 );
		tile[590].setAttributes( TileType.water, available, false, 2000 );
		tile[591].setAttributes( TileType.grass, available, false, 2000 );
		tile[592].setAttributes( TileType.grass, available, false, 2000 );
		tile[593].setAttributes( TileType.grass, available, false, 2000 );
		tile[594].setAttributes( TileType.grass, available, false, 2000 );
		tile[595].setAttributes( TileType.grass, available, false, 2000 );
		tile[596].setAttributes( TileType.grass, available, false, 2000 );
		tile[597].setAttributes( TileType.grass, available, false, 2000 );
		tile[598].setAttributes( TileType.grass, available, false, 2000 );
		tile[599].setAttributes( TileType.grass, available, false, 2000 );
		tile[600].setAttributes( TileType.grass, available, false, 2000 );
	}
	
	public Tile getTile( int i )
	{
		return tile[i];
	}
}
